### PR TITLE
Added Landing Page

### PR DESCRIPTION
**Pull request by munjalSaksham71**
Screenshot 2022-01-28 at 8 58 00 PM

This is the UI

### CODE REVIEW

**Comment by harshitadaswani** [comment]
The code looks clean! Just a suggestion to use shorthand properties to optimize the code
for eg: flex-flow instead of using both flex-direction and flex-wrap

**Comment by munjalSaksham71** [comment]
> The code looks clean! Just a suggestion to use shorthand properties to optimize the code for eg: flex-flow instead of using both flex-direction and flex-wrap

Thanks a Lot, Will do it now.

**Comment by Raghav888** [comment]
Looks good

**Comment by ajit-sharmaGH** [comment]
Looks cool 😎

**Pull request merged**
