### PR TITLE
docs: For Avatar and fix: link button

### PR DESCRIPTION
**Pull request by munjalSaksham71**

### CODE REVIEW

**Review by JantuDeb — APPROVED** [review]
No issue with this changes, you can merge it.

**Review by ultronjs — APPROVED** [review]
Looks good to merge. But a suggestion to use rem in place of px in avatar CSS

**Comment by munjalSaksham71** [comment]
> Looks good to merge. But a suggestion to use rem in place of px in avatar CSS

Okay Cool! I will do it now. Thanks

**Comment by t007rushi** [comment]
You can also use % in case of images else everything looks clean merge it

**Pull request merged**
